### ISSUE TITLE
Migrating dependencies from bower to npm

### ISSUE THREAD

**Issue by xamoom-pali** [pierrickrouxel/ember-cli-bootstrap-colorpicker#3]
Ember now suggests moving from bower deps to npm. Would it be possible to move ember-cli-bootstrap-colorpicker's deps to satisfy the recommendation?

Some inspiration here: [ember-cli-g-maps (Can we remove Bower Dependency)](https://github.com/Matt-Jensen/ember-cli-g-maps/issues/90)

**Comment by pierrickrouxel** [comment]
Done
